package com.dailystudio.tflite.example.reinforcementlearning.fragment

import org.tensorflow.lite.examples.reinforcementlearning.fragment.PlayerBoardCellsListFragment

class PlayerBoardCellsFragment: PlayerBoardCellsListFragment()